# cmt configuration file

# General options
message_only = false
no_diff_stats = false
show_raw_diff = false
context_lines = 12
max_lines_per_file = 500
max_line_width = 300

# AI provider options
provider = "claude" # Options: "claude", "openai"
# model = "claude-3-7-sonnet-latest"  # Uncomment to set a specific model
# temperature = 0.3  # Uncomment to set a specific temperature

# Git options
include_recent_commits = true
recent_commits_count = 5

# Template options
# template = "conventional"  # Uncomment to use a specific template

# You can add a default hint that will be used for all commits
# hint = "Focus on the technical details"
