name: Test Install Script

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed
    branches:
      - main
  pull_request:
    paths:
      - 'scripts/install.sh'
      - '.github/workflows/test-install.yml'

jobs:
  test-install:
    # Only check workflow success on workflow_run events
    if: ${{ github.event_name == 'pull_request' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            shell: bash
            sudo: sudo
          - os: macos-latest
            shell: bash
            sudo: sudo
          - os: windows-latest
            shell: msys2 {0}
            sudo: ""

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: curl

      - name: Test install script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # First ensure the script is executable
          chmod +x ./scripts/install.sh

          # Run the script
          ./scripts/install.sh

          # Verify cmt is installed and executable
          which cmt
          cmt --version

      - name: Test install script via curl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Remove previous installation
          ${{ matrix.sudo }} rm -f $(which cmt)

          # Set branch based on event type
          export BRANCH="${{ github.event_name == 'pull_request' && github.head_ref || 'main' }}"

          # Test the curl installation method
          curl -sSL "https://raw.githubusercontent.com/clifton/cmt/${BRANCH}/scripts/install.sh" | sh

          # Verify cmt is installed and executable
          which cmt
          cmt --version